## Use OpenJDK 21 slim image
#FROM openjdk:21-jdk-slim
#
## Set working directory
#WORKDIR /app
#
## Copy JAR file
#COPY target/mail-tracking-system-backend.jar app.jar
#
## Expose port
#EXPOSE 8081
#
## Run application with environment variables
#ENTRYPOINT ["java", "-jar", "app.jar"]