version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mts-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uor_mts
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mts-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mts-backend-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/uor_mts?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
    depends_on:
      - mysql
    networks:
      - mts-network

volumes:
  mysql-data:

networks:
  mts-network:
    driver: bridge