name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Checkout the repository
  checkout-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  # Job 2: Set up JDK and build JAR
  build-jar:
    runs-on: ubuntu-latest
    needs: checkout-repo # This job depends on checkout-repo

    env:
      SPRING_PROFILES_ACTIVE: deploy
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven using deploy profile
        working-directory: UoR_MTS-Backend/mail-tracking-system 
        run: mvn clean package -Dspring.profiles.active=deploy -DskipTests

  # Job 3: Build Docker Image
  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-jar # This job depends on build-jar

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -f ./UoR_MTS-Backend/mail-tracking-system/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/mail-tracking-system/backend:latest

  # Job 4: Push to Docker Hub
  push-docker-image:
    runs-on: ubuntu-latest
    needs: build-docker-image # This job depends on build-docker-image

    steps:
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mail-tracking-system/backend:latest

  # Job 5: Commit deployment profile if needed
  commit-deployment-profile:
    runs-on: ubuntu-latest
    needs: push-docker-image # This job depends on push-docker-image

    steps:
      - name: Commit deployment profile if needed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add src/main/resources/application-deploy.yml || true
          git commit -m "Add deployment profile config [CI]" || echo "No changes to commit"
          git push || echo "No changes to push"
